# With this file, another toolchain to the currently selected one will be used.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "nightly"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl"
]
