# This file gets automatically recognized each time
# we run "cargo check|build|...".

# We need to cross-compile the core library.
[unstable]
build-std = [
    "alloc",
    "compiler_builtins",
    "core",
]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-hedron.json"
# Get maximum performance with all CPU features of the CPU that compiles this.
# See: https://stackoverflow.com/questions/65156743/what-target-features-uses-rustc-by-default
# I'm not sure if this affects crates that use this as library.
rustflags = [
    "-C",
    # without this, Rustc uses only CPU features "fxsr,sse,sse2".
    # "native" activates all fancy CPU features of the CPU that compiles this but the
    # binary probalby not run on older Intel micro architectures.
    "target-cpu=broadwell",
]
