# This file gets automatically recognized each time
# we run "cargo check|build|...".

# We need to cross-compile the core library.
[unstable]
build-std = [
    "alloc",
    "compiler_builtins",
    "core",
]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-hedron.json"
rustflags = ["-C", "link-args=--entry=start"]
